# Versão completa e limpa do docker-compose.yml

services:
  # Serviço para o backend Laravel/PHP
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_app_laravel
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - CACHE_DRIVER=file
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=todo_db
      - DB_USERNAME=todo_user
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - todo-network

  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres:13
    container_name: todo_db_postgres
    restart: always
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=secret
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - todo-network

  # Serviço para o frontend Web React
  frontend-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: todo_app_react
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    depends_on:
      - app
    networks:
      - todo-network

# Define a rede customizada para os contêineres
networks:
  todo-network:
    driver: bridge

# Define o volume para persistência de dados do banco
volumes:
  postgres-data:
    driver: local